### PR TITLE
Layout Improvements and New "All Events" Page

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
I've made further improvements to the layout of the website. 
- The first button at the top is a link to the survey, making it easier to join the community. Before, it was hidden at the bottom of the page. 
- I improved the labels on some buttons. 
- Improved spacing between elements overall

I also added a new "All Events" page. The button is at the end of the regular Events section. It opens a new page with all upcoming and past events listed. 

Can you please test this version out before merging the pull request? Thanks.

### CODE REVIEW

**Comment by ttimbers** [comment]
I'm away until Monday, bit will take a look when I'm back in town.

Tiff

**Comment by BrunoGrandePhD** [comment]
Can someone confirm whether the new layout works for them? Running `jekyll serve` with the repo switched to this `css_tweaks` branch should allow you to preview the website.

**Comment by aliojjati** [comment]
Hi Bruno,

Yes, as we discussed it the other day, I find this one easier to 
navigate and more practical. Thanks for the work.

Are you guys meeting somewhere for tomorrows google hangout ?

Alireza

On 2015-09-24 4:44 PM, Bruno Grande wrote:

> Can someone confirm whether the new layout works for them? Running 
> |jekyll serve| with the repo switched to this |css_tweaks| branch 
> should allow you to preview the website.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ttimbers/studyGroup/pull/42#issuecomment-143081149.

## 

Alireza

**Comment by BrunoGrandePhD** [comment]
I'll proceed with merging this pull request and we can revert if ever there are glaring issues. This way, the survey link is front and centre.

**Pull request merged**
